config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'home#index'

  resources :packages do
    resources :reviews
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/package.rb
class Package < ApplicationRecord
  validates :name, :description, :price, :presence => true
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  validates :content, :rating, :presence => true
  belongs_to :package
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :only => [:new, :edit] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end
  def index
    @packages = Package.all
  end
  def show
    @package = Package.find(params[:id])
  end
  def new
    @package = Package.new
  end
  def create
    @package = Package.new(package_params)
    if @package.save
      redirect_to  package_path(@package)
    else
      render :new
    end
  end
  def edit
    @package = Package.find(params[:id])
  end
  def update
    @package= Package.find(params[:id])
    if @package.update(package_params)
      redirect_to packages_path
    else
      render :edit
    end
  end
  def destroy
  @package = Package.find(params[:id])
  @package.destroy
  redirect_to packages_path
end
private
  def package_params
    params.require(:package).permit(:name, :description, :price)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :only => [:new]

  def new
    @package = Package.find(params[:package_id])
    @review = @package.reviews.new
  end
  def create
    @package = Package.find(params[:package_id])
    @review = @package.reviews.new(review_params)
    @review.user = current_user

    if @review.save
      redirect_to package_path(@review.package)
    else
      render :new
    end
  end
  def edit
    @package = Package.find(params[:package_id])
    @review = Review.find(params[:id])
  end
  def update
    package = Package.find(params[:package_id])
    @review= Review.find(params[:id])
    if @review.update(review_params)
      redirect_to package_path(package)
    else
      render :edit
    end
  end
  def destroy
    @package = Package.find(params[:package_id])
    @package.destroy
    redirect_to packages_path
  end

private
  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
    current_user && current_user.admin
  end
end

app/views/home/index.html.erb
<h2>Photos with class</h2>

<p>Here at Smiles for Miles we care about your family. We don't just put our heart into the photos, we put our sould in, too. Because who else is gonna? Not Greg. Shut up, Greg. Next time you need photos with a little soul, hit up Miles of Smiles and we will treat you right.</p>

<h2>A legacy of greatness</h2>

<p>Founded in 1776, our great country has nothing to do with our great photography company (except how great they both are). Have you ever wondered, where can I get photos that are just great? Us too. Please, if you find someone, let us know.</p>

<h2>Because you shouldn't have to</h2>

<p>Why depend on your smartphone to take pictures? It doesn't have the capacity to give you the quality you <em>deserve</em>. Take it from us, a quality photo is worth a thousand words and just as many dollars. That's why are pricing is so ridiculous. Company policy.</p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="jumbotron">


      <h1>Miles of Smiles</h1>
      <div class="nav">
        <ul>
          <li class = nav nav-tab><%= link_to "All Packages", packages_path %></li>
          <% if !current_user %>
          <li class = nav nav-tab><%= link_to "Sign In", new_user_session_path %></li>
          <% else %>
          <li class = nav nav-tab><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% end %>
          <% if is_admin? %>
          <li class = nav nav-tab><%= link_to "New Package", new_package_path %></li>
          <% end %>
          <%= yield(:navbar) %>
        </ul>
      </div>
    </div>
<div class="container">
  <%= yield %>
</div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= render('layouts/errors', :object => @review) %>

<%= form_for [@package, @review] do |f| %>
  
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/edit.html.erb
<% content_for(:title, "Miles of Smiles | Edit Review") %>

<h1>Edit this review</h1>

<%= render "form" %>

app/views/reviews/new.html.erb
<% content_for(:title, "Miles of Smiles | New Review") %>

<h1>New Review</h1>

<%= render "form" %>